// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgUSMcB-LEY_N5Ul0CagZxTel0ZA44n7Y',
    appId: '1:954992740619:web:0a3d544789582c2fd2ba0e',
    messagingSenderId: '954992740619',
    projectId: 'collegenotes-b96aa',
    authDomain: 'collegenotes-b96aa.firebaseapp.com',
    storageBucket: 'collegenotes-b96aa.firebasestorage.app',
    measurementId: 'G-YD77639FFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8g-SxdExS9KBc2XG_q6UmLL-hfY818ns',
    appId: '1:954992740619:android:1e221b92e1263fecd2ba0e',
    messagingSenderId: '954992740619',
    projectId: 'collegenotes-b96aa',
    storageBucket: 'collegenotes-b96aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwS2tv8txGhgE8zRcT_oyJ7ye4KdA2npU',
    appId: '1:954992740619:ios:b050e72ed143c152d2ba0e',
    messagingSenderId: '954992740619',
    projectId: 'collegenotes-b96aa',
    storageBucket: 'collegenotes-b96aa.firebasestorage.app',
    iosBundleId: 'com.example.collegeNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwS2tv8txGhgE8zRcT_oyJ7ye4KdA2npU',
    appId: '1:954992740619:ios:b050e72ed143c152d2ba0e',
    messagingSenderId: '954992740619',
    projectId: 'collegenotes-b96aa',
    storageBucket: 'collegenotes-b96aa.firebasestorage.app',
    iosBundleId: 'com.example.collegeNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgUSMcB-LEY_N5Ul0CagZxTel0ZA44n7Y',
    appId: '1:954992740619:web:6e81977ee6caafefd2ba0e',
    messagingSenderId: '954992740619',
    projectId: 'collegenotes-b96aa',
    authDomain: 'collegenotes-b96aa.firebaseapp.com',
    storageBucket: 'collegenotes-b96aa.firebasestorage.app',
    measurementId: 'G-XGY94SJDPL',
  );
}
